# Generated by Django 4.2.1 on 2023-05-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='block',
        ),
        migrations.AddField(
            model_name='transaction',
            name='block',
            field=models.ManyToManyField(related_name='transaction', to='blockchain_app.block'),
        ),
    ]
