# Generated by Django 4.2.1 on 2023-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0002_remove_transaction_block_transaction_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
