# Generated by Django 4.2.1 on 2023-05-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0002_block_wallet_remove_transaction_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
